travis:
  secure:
    BINSTAR_TOKEN: cFhO98uzd6FSmSSCzA3Z3ME4uQKifQBo/5bDxPTKmuvwDSAexHM/EZiPOACKe7TxtJB5vAaB88yV+cejAhZAFbUp3CGDxCTL6/C4YN4NvkUNA1nLjWD1+0OeOauUI3s1RfpUnMOFglGw6WHNBV90x+4peeJIoQ6eLmjratG9fRPcI/HDXqSxf6x7LDi1I/1XxOyZ3EBMyXLpEJsd+HBittj7cbizaJbxS/5O4uMKL60DkvxK1jIoTmRRPVSazEm1GSNuxqEGi/NlAX5ve8n+QPjMZf016Edfx054QHFaq5gc7OGWU+bQhPxJh70xAvNzlJSQ3ys4zlOhtsboU5PrN5F0u4vMvEuLAy7tUrJJ6+rK89rSkhN1xvPywTa5ixul7UqYgPh0MF+XvPo1xP9BclrUBIxACgg4IxXTp+plkEwM0iDmYINYP8ogH4H1jFAbIlESCnAZg2INqfId1ubnEzBtlio+3VaSMinEe1Y8h0dd0TZBypL/91/bcgHSD53tPm/Kw9Ca2oBcUmWWSUbSHv7I1T8Dql7KZxmlvaGCdWsKksf5YswdsV5sUpKuLJvUeyjj2puxI46aux9N2buz4nwsLUesKdebtmO4cyRJ44ChyevvFoUaFJFty10K5p/17kja4isUpKt6y9jZ5gNgrXwzsCedLNuQ6RhPiaDvoDY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
