travis:
  secure:
    BINSTAR_TOKEN: JHTDDv3SlkkmHCvTsaGdmV8WA7fTsAYrFmfSuwgqKkfSMAnur/bz2P65M1GKvZ8w7R6gggrehWBWWj5jEbSuWIsP3TVooW66Nd0zWQfxfunr70kEvjiaIKx+z5pJ69wkK+593PZVrbeZb669y7pJ0WAcHULy1sIqdTvgnKGvUs0VuerK+MkbmysMRIIX3KXzo3caQDspIo+Jsg9wAvqqkT+1tYz1kso5jh31lwrxoHk1QU9/pBvG07QSxcjr++gyodoDTx+c87/dEUo+yyZvL+awRgqHXkqds+ZSrm1hr+0ZAYFdS9dFFiyh/q3izg4vX7PO1Tigp4u4J4sdmYFzBkaZJZIMvC4V5tPh2iGBh7cmWKSDpbdY8J9GZGfBIHXmmInN3kJBOCQpT4jj3qkdUo6GB61ux8MB9W961NVgUvKor/ObFr356G3OolOrrFFbUGvJ8XNxCtk2wiMc/7vv+AiK/J30Hb25N4RwCNUHOk65vibO/2FGvceRsm/2Fw6spc/gStdGEtDnoqksetopQItrHUuXoBEgzt3OfFgnYaaD7NDrfRktkJA4tId+fSEIxRwbca0eGrp6da95TUeVRUU8GUG4WMRTqYBad4JQcSAGgVDxvDIvB46jIkECTvVcuWEklcwVxv4lY8jQfjY02ZUOZvTrLfqyUYPSuUIHNR0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
